### ISSUE TITLE
Multiple shooting is slow

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#139]
I am trying to use multiple shooting on a intermediately to large problem, and it is prohibitively slow from both slow evaluations and poor convergence. Currently, performance is significantly worse than where we were a year ago in this aspect.

**Comment by msparapa** [comment]
ugh I've been noticing the same thing. I thought it was related to my reconstruction but you might be right, this could be a more general issue. I suspect the Jacobian function is mutating one of the states, which then gets fed back through to the original gamma's. I'll focus on this tonight.

**Comment by msparapa** [comment]
Can you upload an example problem where you see this is the case? None of mine become "horribly slow", just slower than I'd expect.

**Comment by msparapa** [comment]
@SeanMatthewNolan checkout out shooting's test case T24 I just added as a part of #164. I couldn't solve it without using a continuation, nor could I solve it with less than 4 arcs. It's a "pure" bvp problem as opposed to a control problem with PMP. I think you should use this test case when checking speed of multiple shooting since it shouldn't be bottle-necked by things like control calculations. For reference, [this](https://archimede.dm.uniba.it/~bvpsolvers/testsetbvpsolvers/?page_id=247) is T24.

**Comment by SeanMatthewNolan** [comment]
Thanks, I'm working on this now, so I'll use that

**Comment by msparapa** [comment]
Also check out T25-T26. These problems actually simulate entering and exiting a path constraint pretty well, despite it not having a path constraint. T27 would be better but I couldn't get it to converge for VHARD (`const=1e-3`). You might also find

```
python -m pytest beluga/bvpsol/tests/test_Shooting.py
```

to be a useful command since it'll output the time taken to run all the shooting test cases. The majority of the time is spent on the multiple shooting problems.

**Comment by msparapa** [comment]
@SeanMatthewNolan give multiple shooting a try now with your Armijo root-solver. Final changes should be pushed to master branch right now. My sparse formulation is giving us some pretty huge performance gains. It doesn't seem to be as fast as sparse collocation, but it's way faster than it was before. I haven't tried multiple shooting on several processors but I think that would be the next step. Probably a topic for a different issue.

**Comment by SeanMatthewNolan** [comment]
Everything seems good to me! Sorry, for the delay, but let's close this then.  Thanks
