### ISSUE TITLE
find a better way to prevent shooting methods from stalling

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#15]
We're using with timeout(seconds=5000): which apparently has issues on different OS's.

**Comment by msparapa** [comment]
@SeanMatthewNolan are there any cases you have where this occurs? I remember we talked about this briefly, but I don't remember where this came up or what the issue was. We're running test cases on multiple OS's right now and I haven't seen any issues so far.

**Comment by SeanMatthewNolan** [comment]
@msparapa I don't have any easily available for the recent versions. This does seem to be less of an issue with the new scipy solver instead of that old one we used. This may not sound consistent with my previous comments, but it is probably best to gut this feature and add it back in when/if an issue arises with a particular problem.

**Comment by msparapa** [comment]
Cool. If we run into issues in the future we can revisit this. Though 5000s is a massive time for a single integration so, as it was in this case, if it happens again there's probably a different much larger issue.
