### ISSUE TITLE
Constants are output scaled

### ISSUE THREAD

**Issue by SeanMatthewNolan** [Rapid-Design-of-Systems-Laboratory/beluga#192]
Values of constants need to be unscaled before output

**Comment by msparapa** [comment]
Are you sure this is the case? I've tried several examples and it seems like the values of the constants are fine on output. I'm checking the `sol.aux['const']` values.

**Comment by msparapa** [comment]
This one got me after I tried to reuse the compute_control function outside of beluga. I got rid of most, if not all the uses of `.aux['const']` and replaced them with just `.const`. I had to send in the raw bvp data to continuation because each trajectory no longer tracks what the names of the constants are, just the values.

Scaling was fixed in the process.
