### ISSUE TITLE
Output costate values do not appear to be scaled properly

### ISSUE THREAD

**Issue by msparapa** [Rapid-Design-of-Systems-Laboratory/beluga#70]
Running dynamically similar problems results in the costate time histories having similar shape, but wildly different numerical values. I suspect they aren't being scaled and unscaled properly.

**Comment by SeanMatthewNolan** [comment]
Something related to this that has never been clear to me is whether the path cost should be given the units of the integrand or integral in the solver. This is how the units for the costates should be determined so that the Hamiltonian is dimensionally consistent. The control and state histories will be the same for both Mayer and Lagrange form problems only effecting the relative size of the costates, but  it is important for Bolza form problem, so we should make sure that whatever we choose is noted in the documentation and is consistent with the other unit definitions.

**Comment by msparapa** [comment]
We should give units in terms of the stuff under the integral, the Lagrangian L. So the planarHypersonic case has m^2/s^2, which makes sense. I'm noticing that the brachistochrone has L=1, with units of "s". That's probably not right. `optimlib` should add the "s" in automatically because the units of time are "s", and thats defined elsewhere.

I'm also noticing that the hypersonic 3DoF problem was using -v as a cost with units of m/s instead of -v^2 and m^2/s^2, so thats where my problem was coming from. There's actually no problem with scaling as far as I can see now.
